### ISSUE TITLE
Useless Error Message When Authentication Fails

### ISSUE THREAD

**Issue by wortho** [NAVPERF/NAV2016-Sample#1]
If the client session fails to authenticate then the error message is something like:

"Test method Microsoft.Dynamics.Nav.LoadTest.OrderProcessorScenarios.OpenCustomerList threw exception: 
System.InvalidOperationException: Communication error was thrown:
System.ServiceModel.CommunicationException: Error while copying content to a stream. ---> ..."

This is because the server returns a standard HTTP error response instead of the expected JSON content.

The error handling could be improved to give a more meaningful error message.

**Comment by freddydk** [comment]
I think this is because you are trying to connect to a NAV 2017 server with the NAV 2016 assemblies. I am uploading a NAV 2017 version of the sample now (with new DLL's from the 2017 DVD)

**Comment by wortho** [comment]
Freddy that issue was from one year ago. It was in response to feedback from the hands on labs.
